### ISSUE TITLE
有配套的博客或者测试案例可以看不？

### ISSUE THREAD

**Issue by Bian-Sh** [chenwansal/UnityDirtyCompiler#3]
个人感觉在 Unity assembly definition file 的加持下，编译已经是你期望的那种只编译 有修改的程序集的样子了？

另外，你说的仅 Runtime 有效是啥意思呢？ 有点不明确呀。
runtime 可以理解从成： Assembly-CSharp.dll 里面的逻辑吗？
或者是供应用打包后的使用的那种 dll （最大特点是 编辑器下的宏包裹的逻辑不被编译）？

然后，AssemblyBuilder Unity 官方给的说明是这玩意是编译 Assets 之外的程序集的呀。
我试过用这个编译 assets 内的程序集，会导致 project 下的 .sln 和 .csproj 完全被修改导致ide需要重新加载项目(我比你多了一个这样的配置： builder.referencesOptions = ReferencesOptions.UseEngineModules;)

仅作学习探讨

**Comment by chenwansal** [comment]
你好，在最新的2021已经支持了“进入场景不重载程序域”的功能，因此该库仅支持2019版的Unity。

2019版下的Unity进入PlayMode前会有两次重载程序域的操作：
第一次：编写完脚本，回到Unity编辑器时（手动Ctrl+R或自动刷新）
第二次：进入PlayMode时
DirtyCompiler主要是可以跳过第一次重载程序域，仅编译改动的脚本。

到了2021，通过ProjectSetting/Editor -> 去掉Reload Domain的勾，可以实现只重载第一次程序域。
在这种情况下，要在主入口OnDestroy或OnApplicationQuit时把程序恢复至初始状态（比如清空缓存、重置静态数据为初始值），避免出错。
