### ISSUE TITLE
插件导入 不需要额外设置吗

### ISSUE THREAD

**Issue by ZeroUltra** [chenwansal/UnityDirtyCompiler#4]
我使用的2021.3+vs2019
如果要`ctrl+t`编译 我要关闭`Auto Refresh`  还要设置vs中unity
![image](https://user-images.githubusercontent.com/38253805/196872826-92ad2a62-9588-4c81-8b4a-001c155f77f3.png)

**Comment by chenwansal** [comment]
Unity 2021已经改了编译的流程，不需要使用该插件。

如果是Unity 2019.4，需要关掉AutoRefresh，然后在Unity编辑器里按Ctrl+T编译。

**Comment by ZeroUltra** [comment]
好的哦 但是编译还是慢 挺烦人的

**Comment by chenwansal** [comment]
2021.3 在Unity菜单里：Editor/ProjectSettings/Editor 选项里，有个"Enter Play Mode Settings"，把ReloadDomain的勾去掉，这样在没有修改代码的情况下重新进入PlayMode不需要重新编译。
（注：这种方式需要代码架构的支持，比如OnApplicationQuit里要把缓存清干净。）

另一种方式是：直接用mcs（Mono的编译器）编译改动的csproj，具体方法可以上网搜。

**Comment by ZeroUltra** [comment]
感谢回复,第一种方案我试过,一些静态数据必须要自己手动清理,有些许麻烦
我看看第二种

**Comment by ZeroUltra** [comment]
感谢回复,第一种方案我试过,一些静态数据必须要自己手动清理,有些许麻烦
我看看第二种
